Added dynamic reconfigure, auto white balance
iron-ox/pylon_camera pull request #1
Opened 2017-06-08 18:49 UTC by lwan

Exposed current camera settings to dynamic reconfigure: 
- Gain (and auto gain toggle)
- Brightness (and auto brightness toggle -- neither seem to do anything to the image)
- Exposure (and auto exposure)
- Gamma
- Auto white balance enable

Other settings will need additional hooks into the Pylon API (custom white balance setttings, trigger settings, etc.)

Also set default MTU from 3000 to 1500 in case it's not set in the .launch file.

2017-06-08 19:50 UTC, jonbinney requested changes

2017-06-08 19:50 UTC, jonbinney commented on package.xml
> +  <run_depend>roslint</run_depend>
Why did you make roslint a run_depend?

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/main.cpp
> +    dynamic_reconfigure::Server<pylon_camera::CameraSettingsConfig>::CallbackType f;
This shouldn't be in `main()` now, right? You moved it to the PylonCameraNode class.

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/main.cpp
> +
Remove white space. Actually `main.cpp` should probably not have any changes at all in this PR.

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/pylon_camera_node.cpp
> +
Try not to make whitespace changes in a feature PR unless there is a strong reason to. They make it harder to find the real changes in the diff.

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/pylon_camera_node.cpp
> +                                                                     camera_control_msgs::SetBool::Response >(
Is this just a whitespace change?

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/pylon_camera_parameter.cpp
> +    if ( nh.hasParam("whitebalance_auto") )
Dynamic reconfigure should call your callback with the values set as ROS params at startup - is there a reason you also check the parameter manually here?

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/pylon_camera_parameter.cpp
> +    ROS_INFO_STREAM("Reading parameters from paramter server");
Spelling: `paramter`

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/pylon_camera_parameter.cpp
>          downsampling_factor_exp_search_(1),
Can we get rid of this `PylonCameraParameter` class completely and replace it with the one that dynamic-reconfigure generates automatically? That will require adding the remaining parameters to dynamic_reconfigure (e.g. `mtu_size`), but that will be a good idea anyway.

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/pylon_camera_node.cpp
> +                                                                     camera_control_msgs::SetBool::Response >(
Actually, screw backwards compatibility in this case. Can you just get rid of the individual parameter setting services? They are obsolete once we can change things with dynamic_reconfigure.

2017-06-08 19:50 UTC, jonbinney commented on src/pylon_camera/pylon_camera_parameter.cpp
> +        std::cout << "continuous auto white balance set" << std::endl;
Don't use `cout` here. If you need to output, use `LOG_INFO`.

2017-06-08 20:10 UTC, lwan commented on package.xml
> +  <run_depend>roslint</run_depend>
Bad habit to make build_depends also run_depends. Will take out.

2017-06-08 20:10 UTC, lwan commented on src/pylon_camera/main.cpp
> +    dynamic_reconfigure::Server<pylon_camera::CameraSettingsConfig>::CallbackType f;
Yep. Taking it out.

2017-06-08 20:12 UTC, lwan commented on src/pylon_camera/main.cpp
> +
Will do. Reverting changes to `main.cpp`

2017-06-08 20:13 UTC, lwan commented on src/pylon_camera/pylon_camera_node.cpp
> +
Will remove.

2017-06-08 20:13 UTC, lwan commented on src/pylon_camera/pylon_camera_node.cpp
> +                                                                     camera_control_msgs::SetBool::Response >(
Yep. I'll remove the services per our conversation today.

2017-06-08 20:15 UTC, lwan commented on src/pylon_camera/pylon_camera_parameter.cpp
>          downsampling_factor_exp_search_(1),
Yep, this should be removed as part of moving everything to dynamic reconfigure.

2017-06-08 20:16 UTC, lwan commented on src/pylon_camera/pylon_camera_parameter.cpp
> +    ROS_INFO_STREAM("Reading parameters from paramter server");
Okey doke. Will change.

2017-06-08 20:20 UTC, lwan commented on src/pylon_camera/pylon_camera_parameter.cpp
> +    if ( nh.hasParam("whitebalance_auto") )
@jonbinney:  
Wouldn't I want to see if the parameter is already set? Dynamic reconfigure should be setting it at startup, but what if the launchfile sets a different value?

2017-06-08 20:21 UTC, lwan commented on src/pylon_camera/pylon_camera_parameter.cpp
> +        std::cout << "continuous auto white balance set" << std::endl;
Will do.

2017-06-08 20:29 UTC, jonbinney commented on src/pylon_camera/pylon_camera_parameter.cpp
> +    if ( nh.hasParam("whitebalance_auto") )
Dynamic reconfigure actually does this. It checks for a ROS parameter with the name of the parameter at startup. So if you set it in the launchfile, dynamic reconfigure will pass that value to your callback.

2017-06-13 07:51 UTC, lwan commented on src/pylon_camera/pylon_camera_parameter.cpp
> +        std::cout << "continuous auto white balance set" << std::endl;
Any reason not to use `ROS_INFO_STREAM` ?

2017-06-13 15:15 UTC, jonbinney commented on src/pylon_camera/pylon_camera_parameter.cpp
> +        std::cout << "continuous auto white balance set" << std::endl;
ROS_INFO_STREAM is fine too - as long as the output goes through the ROS logging system.

2017-06-14 03:33 UTC, lwan commented on package.xml
> +  <run_depend>roslint</run_depend>
@jonbinney doesn't look like it'll build without roslint as a run_depend:

`CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:224 (message):
  catkin_package() DEPENDS on the catkin package 'roslint' which must
  therefore be listed as a run dependency in the package.xml
Call Stack (most recent call first):
  /opt/ros/kinetic/share/catkin/cmake/catkin_package.cmake:102 (_catkin_package)
  pylon_camera/CMakeLists.txt:40 (catkin_package)
`

2017-06-14 22:59 UTC, jonbinney commented
Looks good!

2017-06-14 22:59 UTC, merged